### PR TITLE
Add wireframes

### PR DESCRIPTION
**Pull request by piechowski**
Added wireframe of the Phone App proposal.

### CODE REVIEW

**Comment by grepsedawk** [comment]
What application was this done in? Balsamiq?

**Comment by piechowski** [comment]
Yes balsamiq

**Comment by grepsedawk** [comment]
Don't forgot to pull latest master prior to branching off of it

**Comment by grepsedawk** [comment]
Thanks for creating this, it really helps out on knowing what the interface is.

**Pull request merged**
